version: '3.8'

services:
  stackedit:
    build: ./stackedit-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./stackedit-server:/app
      - /app/node_modules 